Adding $override parameter to cc and bcc which is now available in th…
Cyber-Duck/Mail-Grasp pull request #2
Opened 2017-01-03 19:11 UTC by worzy

…e illuminate/mail package and breaks the tests

Change was made here: https://github.com/laravel/framework/commit/acd826e5f0d517bf7703cf2de598e4a54181f60d#diff-31f3755767eaffe4a66b232017c45a5f

2017-01-03 21:08 UTC, SimoTod requested changes

2017-01-03 21:08 UTC, SimoTod commented on src/Support/Message.php
> +    public function cc($address, $name = null, $override = false)
Cool, thanks.
If override == true, I think we should reset the array (see function to() row 39) to keep the class consistent with the real implementation.

2017-01-03 21:08 UTC, SimoTod commented on src/Support/Message.php
> +    public function bcc($address, $name = null, $override = false)
Same as above

2017-01-04 08:47 UTC, worzy commented
The arrays have been reset to match the "to" function and the Laravel implementation.

2017-01-04 16:23 UTC, SimoTod approved these changes

2017-01-04 16:25 UTC, merged